from git.repo.base import Repo

def git_init(path: str) -> Repo: ...
def git_config(repo: Repo, *args: str) -> None: ...
def get_git_repository(path: str) -> Repo | None: ...
def git_add_path(
    repo: Repo | None, path: str, msg: str, commit=True, verbose=False
) -> None: ...
def git_remove_path(
    repo: Repo | None, path: str, msg: str, recursive=False, commit=True, verbose=False
) -> None: ...
